### ISSUE TITLE
docker compose & CMD line args

### ISSUE THREAD

**Issue by Zixim** [mtlynch/picoshare#314]
Thank you very much for this great tool !!

The new command line argument `-vacuum` prompts this question.
What is the correct way of adding this to a docker compose file ?
This is my current compose, to which I would like to add the vacuum argument : 
```
version: '2'
services:
  picoshare:
    image: mtlynch/picoshare:latest
    restart: unless-stopped
    ports:
      - 3002:3002
    environment:
      - PORT=3002
      - PS_SHARED_SECRET=**********
    volumes:
      - /mnt/picoshare:/data
```

Should I add a line like `command: -vacuum -db /data/store.db` in there ? Is there a "better" way ?
