### ISSUE TITLE
Container doesn't run behind Nginx Proxy Manager

### ISSUE THREAD

**Issue by DarkCeptor44** [mtlynch/picoshare#361]
I deployed the latest (as of now) Docker image for Picoshare on my ARM64 Orange Pi Zero 2 and assigned the port 4001, it works if I use the device's IP or hostname with the port like `http://orange.lab:4001` but using NPM it doesn't even open the page, currently NPM is on a docker container as well but not in host network mode, I use the device's IP directly (in 10.4.0.0/24 subnet) to proxy a domain name to a specific port and Pi-Hole to redirect the domain to the device domain name, and it has been working with other applications, even outside of Docker.

I tried rolling back to 1.1.3 as suggested in #255 but nothing changed, this is what happens when I open `http://pico.lab/`:
![picoshare-npm](https://user-images.githubusercontent.com/16278483/211915964-20c8acee-6959-418a-a053-ed4f7a90fcd6.png)

This is the logs from the container after launching it and opening the tab, acquired through `docker-compose logs`:
```
Attaching to picoshare
picoshare    | ++ echo false
picoshare    | + PS_LAUNCH_CMD='/app/picoshare -db /data/store.db'
picoshare    | + [[ false == \t\r\u\e ]]
picoshare    | Starting without litestream
picoshare    | + echo 'Starting without litestream'
picoshare    | + eval '/app/picoshare -db /data/store.db'
picoshare    | ++ /app/picoshare -db /data/store.db
picoshare    | 2023/01/11 20:34:49 initializing random seed
picoshare    | 2023/01/11 20:34:49 main.go:22: Starting picoshare server
picoshare    | 2023/01/11 20:34:49 sqlite.go:41: reading DB from /data/store.db
picoshare    | 2023/01/11 20:34:49 migrations.go:33: Migration counter: 5/5
picoshare    | 2023/01/11 20:34:49 main.go:51: Listening on 4001
```

From the browser image it looks like it's forcing https and I can't even force it back to http, but I didn't setup https for anything in NPM or this device, and trying to in NPM doesn't work either.

I just realized that I never posted the docker-compose file so here it is:
```yaml
version: '3.3'
services:
  picoshare:
    image: mtlynch/picoshare:latest
    container_name: picoshare
    environment:
      - PORT=4001
      - PS_SHARED_SECRET=abcdef
    ports:
      - 4001:4001
    command: -db /data/store.db
    volumes:
      - /home/darkceptor44/docker/data/picoshare/data:/data
      - /home/darkceptor44/docker/data/picoshare/temp:/tmp
    restart: unless-stopped
```
