### ISSUE TITLE
how to use command "-vacuum" ?

### ISSUE THREAD

**Issue by bg8ioi** [mtlynch/picoshare#436]
I found the vacuum is not work as well , maybe I make a mistake code , below is my docker-compose.yml 

```yaml
version: "3.2"
services:
  picoshare:
    image: mtlynch/picoshare
    environment:
      - PORT=4001
      - PS_SHARED_SECRET=000000 # Change to any password
    ports:
      - 4001:4001
    command: -db /data/store.db -vacuum 
    volumes:
      - ./data:/data
```
