### ISSUE TITLE
Gateway Timeout

### ISSUE THREAD

**Issue by tiritibambix** [mtlynch/picoshare#438]
Hello !

First, I'd like to say that Picoshare is one hell of an app. It already has helped me a lot sharing stuff with friends and family. So thank you :)

I was trying to upload a 1.5Go zip file today for a friend to download when I had an issue.
`File uploaded! Processing...`
And after a couple minutes
`Gateway Timeout`

I use docker and here is my docker-compose:
```
version: '3.3'
services:
    picoshare:
        environment:
            - PORT=3001
            - PS_SHARED_SECRET=complicatedpassword
            - PS_BEHIND_PROXY=true
        ports:
            - '3001:3001/tcp'
        command: -db /data/store.db
        volumes:
            - './Picoshare/data:/data'
        container_name: picoshare
        image: mtlynch/picoshare
        restart: unless-stopped
```

Picoshare is behind a reverse proxy. I use [Nginx Proxy Manager](https://github.com/NginxProxyManager/nginx-proxy-manager)

I see nothing relevant in the [logs](https://clip.steph.click/-jNiafz6sBB)

Can you help me ?
