### ISSUE TITLE
DB Path

### ISSUE THREAD

**Issue by sfreek76** [mtlynch/picoshare#655]
Hello

Not a bug, but having issue installing picoshare: Trying to install picoshare on Docker Desktop on MacOS Monterey. Install works but since I have a very small system partition i would like the database to be located on a bigger, external volume. So I tought I will change the data path but all it does is to create a folder in my users folder on my system partition, not on my designated volume. What I am doing wrong? Thanks in advance!

My docker run looks like this:
```
docker run \
  --env "PORT=4001" \
  --env "PS_SHARED_SECRET=somesecretpass" \
  --publish 4001:4001/tcp \
  --volume "${PWD}/Volumes/Shadowfax HD 2/picoshare/data:/data" \
  --name picoshare \
  mtlynch/picoshare
```

**Comment by sfreek76** [comment]
Got it to work! Had to go with docker compose and now it works with my designated path to an external volume...

In case anyone has the same issue, here's how my Docker-Compose.yml looks like:
```
version: "3.2"
services:
  picoshare:
    image: mtlynch/picoshare
    environment:
      - PORT=4001
      - PS_SHARED_SECRET=mypassword # Change to any password
    ports:
      - 4001:4001
    command: -db /data/store.db
    volumes:
      - /Your/Pathto/picoshare/data:/data
```
